### ISSUE TITLE
Tests fails

### ISSUE THREAD

**Issue by Diaskhan** [caifl/bpmtk#6]
I have tried to run test, but all fails.
With this error logs!
[tests.txt](https://github.com/caifl/bpmtk/files/3134086/tests.txt)

![image](https://user-images.githubusercontent.com/15046677/57010941-0a0f3480-6c21-11e9-8e94-74e439e98666.png)

Using vs 2017

**Comment by Diaskhan** [comment]
Could U help to pass tests? Please..

**Comment by Diaskhan** [comment]
Could U give me Sql database Dumps to run tests with succes?

**Comment by caifl** [comment]
don't run all tests，you can run the one fork join to start the flow.

**Comment by Diaskhan** [comment]
Could U provide sample Example how to run simple process ?
Wihout Persisting to database ?

Maybe need new project(folder) with some examples !

**Comment by Diaskhan** [comment]
I need some start point!

**Comment by caifl** [comment]
I have upload the Mysql database schema init scripts.

checkout the file 'https://github.com/caifl/bpmtk/blob/master/db/mysql/bpmtk_init.sql'

**Comment by caifl** [comment]
Then run this unitTest.

Fork-Join TestCase:
https://github.com/caifl/bpmtk/blob/master/src/Bpmtk.Engine.Tests/Bpmn/Gateway/NestedForkJoinTestCase.cs

**Comment by caifl** [comment]
Or you can create new project,  like 'ConsoleApp' , and copy code from 'NestedForkJoinTestCase.cs' and 'BpmtkTestCase.cs'.  

The Sample BPMN 2.0 Process:
https://github.com/caifl/bpmtk/blob/master/src/Bpmtk.Engine.Tests/Resources/Gateway/ParallelGatewayTest.testNestedForkJoin.svg

**Comment by Diaskhan** [comment]
By the way bpmn diagram has made it wrong.  
https://github.com/caifl/bpmtk/blob/master/src/Bpmtk.Engine.Tests/Resources/Gateway/ParallelGatewayTest.testNestedForkJoin.svg

By bpmn its not allowed to use exclusive gateway as joining gateway for outgoing parallel gateway !  The model is not workable !

**Comment by Diaskhan** [comment]
Is task A will execute last. Its gonna be error because process already ended !

**Comment by caifl** [comment]
I have write a simple demo in 'ConsoleApp',
Please check out the file:
https://github.com/caifl/bpmtk/blob/master/src/ConsoleApp/Program.cs

**Comment by Diaskhan** [comment]
![image](https://user-images.githubusercontent.com/15046677/57086870-c13ea500-6d20-11e9-9d6e-bf126811803e.png)

Still error))

**Comment by Diaskhan** [comment]
Unhandled Exception: System.AggregateException: One or more errors occurred. (Input string was not in a correct format.) ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Double.Parse(String s)
   at Bpmtk.Engine.Bpmn2.Parser.Handlers.BPMNLabelParseHandler`1.<>c.<.ctor>b__0_0(BPMNLabel parent, IParseContext context, XElement element) in c:\Users\TOTEM\YandexDisk\bpmtk-master\src\Bpmtk.Engine\Bpmn2\Parser\Handlers\BPMNDiagramParseHandler.cs:line 132
   at Bpmtk.Engine.Bpmn2.Parser.ParseHandlerAction`1.Create(Object parent, IParseContext context, XElement element) in c:\Users\TOTEM\YandexDisk\bpmtk-master\src\Bpmtk.Engine\Bpmn2\Parser\IParseHandler.cs:line 23
   at Bpmtk.Engine.Bpmn2.Parser.ParseHandler`1.CreateChildren(Object parent, IParseContext context, XElement element) in c:\Users\TOTEM\YandexDisk\bpmtk-master\src\Bpmtk.Engine\Bpmn2\Parser\IParseHandler.cs:line 46
   at Bpmtk.Engine.Bpmn2.Parser.Handlers.BPMNLabelParseHandler`1.Create(TLabeledShape parent, IParseContext context, XElement element) in c:\Users\TOTEM\YandexDisk\bpmtk-master\src\Bpmtk.Engine\Bpmn2\Parser\Handlers\BPMNDiagramParseHandler.cs:line 150
   at Bpmtk.Engine.Bpmn2.Parser.ParseHandler`1.Bpmtk.Engine.Bpmn2.Parser.IParseHandler.Create(Object parent, IParseContext context, XElement element) in c:\Users\TOTEM\YandexDisk\bpmtk-master\src\Bpmtk.Engine\Bpmn2\Parser\IParseHandler.cs:line 51
   at Bpmtk.Engine.Bpmn2.Parser.ParseHandler`1.CreateChildren(Object parent, IParseContext context, XElement element) in c:\Users\TOTEM\YandexDisk\bpmtk-master\src\Bpmtk.Engine\Bpmn2\Parser\IParseHandler.cs:line 46
   at Bpmtk.Engine.Bpmn2.Parser.Handlers.BPMNShapeParseHandler.Create(BPMNPlane parent, IParseContext context, XElement element) in c:\Users\TOTEM\YandexDisk\bpmtk-master\src\Bpmtk.Engine\Bpmn2\Parser\Handlers\BPMNDiagramParseHandler.cs:line 86
   at Bpmtk.Engine.Bpmn2.Parser.ParseHandler`1.Bpmtk.Engine.Bpmn2.Parser.IParseHandler.Create(Object parent, IParseContext context, XElement element) in c:\Users\TOTEM\YandexDisk\bpmtk-master\src\Bpmtk.Engine\Bpmn2\Parser\IParseHandler.cs:line 51
   at Bpmtk.Engine.Bpmn2.Parser.ParseHandler`1.CreateChildren(Object parent, IParseContext context, XElement element) in c:\Users\TOTEM\YandexDisk\bpmtk-master\src\Bpmtk.Engine\Bpmn2\Parser\IParseHandler.cs:line 46
   at Bpmtk.Engine.Bpmn2.Parser.Handlers.BPMNPlaneParseHandler.Create(BPMNDiagram parent, IParseContext context, XElement element) in c:\Users\TOTEM\YandexDisk\bpmtk-master\src\Bpmtk.Engine\Bpmn2\Parser\Handlers\BPMNDiagramParseHandler.cs:line 52
   at Bpmtk.Engine.Bpmn2.Parser.ParseHandler`1.Bpmtk.Engine.Bpmn2.Parser.IParseHandler.Create(Object parent, IParseContext context, XElement element) in c:\Users\TOTEM\YandexDisk\bpmtk-master\src\Bpmtk.Engine\Bpmn2\Parser\IParseHandler.cs:line 51
   at Bpmtk.Engine.Bpmn2.Parser.ParseHandler`1.CreateChildren(Object parent, IParseContext context, XElement element) in c:\Users\TOTEM\YandexDisk\bpmtk-master\src\Bpmtk.Engine\Bpmn2\Parser\IParseHandler.cs:line 46
   at Bpmtk.Engine.Bpmn2.Parser.Handlers.BPMNDiagramParseHandler.Create(Definitions parent, IParseContext context, XElement element) in c:\Users\TOTEM\YandexDisk\bpmtk-master\src\Bpmtk.Engine\Bpmn2\Parser\Handlers\BPMNDiagramParseHandler.cs:line 29
   at Bpmtk.Engine.Bpmn2.Parser.ParseHandler`1.Bpmtk.Engine.Bpmn2.Parser.IParseHandler.Create(Object parent, IParseContext context, XElement element) in c:\Users\TOTEM\YandexDisk\bpmtk-master\src\Bpmtk.Engine\Bpmn2\Parser\IParseHandler.cs:line 51
   at Bpmtk.Engine.Bpmn2.Parser.ParseHandler.CreateChildren(Object parent, IParseContext context, XElement element) in c:\Users\TOTEM\YandexDisk\bpmtk-master\src\Bpmtk.Engine\Bpmn2\Parser\IParseHandler.cs:line 71
   at Bpmtk.Engine.Bpmn2.Parser.DefinitionsParseHandler.Create(Object parent, IParseContext context, XElement element) in c:\Users\TOTEM\YandexDisk\bpmtk-master\src\Bpmtk.Engine\Bpmn2\Parser\DefinitionsParseHandler.cs:line 47
   at Bpmtk.Engine.Bpmn2.Parser.BpmnParser.Parse(Stream stream) in c:\Users\TOTEM\YandexDisk\bpmtk-master\src\Bpmtk.Engine\Bpmn2\Parser\BpmnParser.cs:line 88
   at Bpmtk.Engine.Bpmn2.BpmnModel.FromBytes(Byte[] bytes, Boolean disableValidation) in c:\Users\TOTEM\YandexDisk\bpmtk-master\src\Bpmtk.Engine\Bpmn2\BpmnModel.cs:line 43
   at Bpmtk.Engine.Repository.DeploymentBuilder.BuildAsync() in c:\Users\TOTEM\YandexDisk\bpmtk-master\src\Bpmtk.Engine\Repository\DeploymentBuilder.cs:line 63
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ConsoleApp.Program.Main(String[] args) in c:\Users\TOTEM\YandexDisk\bpmtk-master\src\ConsoleApp\Program.cs:line 75

**Comment by Diaskhan** [comment]
1.Found error !
The problem was in parsing float 
```
<bpmndi:BPMNLabel>
          <dc:Bounds x="1035.5" y="287" width="35" height="14" />
        </bpmndi:BPMNLabel>
```

**Comment by Diaskhan** [comment]
One more Error!

![image](https://user-images.githubusercontent.com/15046677/57089894-56449c80-6d27-11e9-997b-c87ff9f0a665.png)

**Comment by Diaskhan** [comment]
In time of developing beterr not to use Async. Its hard to Debug!

**Comment by caifl** [comment]
1.   The first double.Parse( string )  error,  mybe Globalization cultures difference.   you can try double.Parse( string, NumberStyle ) to find why throw exception.
 
2.  Change "bpm_token" table  set column "activity_id"  to nullable.

3. There are many important works to be done in this project,  so i have no time to replace Async or add sync method .

**Comment by caifl** [comment]
you can add  Postgres entityframeworkcore nuget package to switch database server.

**Comment by Diaskhan** [comment]
I have tried set nullable 
Change "bpm_token" table set column "activity_id" to nullable.
Its works!

**Comment by Diaskhan** [comment]
Could undesrtand me how deploy process to database?

I will try to make simple UI dev console!

**Comment by Diaskhan** [comment]
By the way
bpm_token" table set column "activity_id" to nullable.
Need to fix!

**Comment by caifl** [comment]
I fixed it by change model configration. (activity_id column)

**Comment by caifl** [comment]
1.  The following lines will deploy bpmn content to Process Repository (create 'bpm_proc_def' table records).

var deploymentBuilder = deploymentManager.CreateDeploymentBuilder();
            var deployment = deploymentBuilder
                .SetCategory("demo")
                .SetName("Demo deployment")
                .SetMemo("A simple process demo for BPMTK.")
                .SetBpmnModel(modelContent)
                .BuildAsync()
                .Result;

2. if you want to create BPMN Modeler and save BPMN Content in database.  There is a  entity class "Package".

**Comment by caifl** [comment]
Create New Package  => Edit BPMN 2.0 in UI => Save  => Publish BPMN Model => deploymentBuilder.SetPackageId(...).SetBpmnModel(...).BuildAsync()
